on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: nextjs-frontend-stackquiz

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout Code
         uses: actions/checkout@v3

       - name: Set TAG from SHA
         run: |
           echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV

       - name: Show TAG value
         run: |
          echo "TAG value is: ${{ env.TAG }}"

       - name: Login to Docker Registry
         run: |
          echo "${{ secrets.PASSWORD }}" | docker login -u ${{ secrets.USERNAME }} --password-stdin

       - name: Build Docker Image
         run: |
          docker build \
            --build-arg GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
            --build-arg GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
            --build-arg GITHUB_CLIENT_ID="${{ secrets.GH_CLIENT_ID }}" \
            --build-arg GITHUB_CLIENT_SECRET="${{ secrets.GH_CLIENT_SECRET }}" \
            --build-arg FACEBOOK_CLIENT_ID="${{ secrets.FACEBOOK_CLIENT_ID }}" \
            --build-arg FACEBOOK_CLIENT_SECRET="${{ secrets.FACEBOOK_CLIENT_SECRET }}" \
            --build-arg NEXTAUTH_URL="${{ secrets.NEXTAUTH_URL }}" \
            --build-arg NEXT_PUBLIC_API_BASE_URL="${{ secrets.NEXT_PUBLIC_API_BASE_URL }}" \
            --build-arg NEXT_PUBLIC_API_URL="${{ secrets.NEXT_PUBLIC_API_URL }}" \
            --build-arg NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}" \
            -t ${{ secrets.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} \
            -t ${{ secrets.USERNAME }}/${{ env.IMAGE_NAME }}:latest .


       - name: Push Docker Image (SHA)
         run: docker push ${{ secrets.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

       - name: Push Docker Image (latest)
         run: docker push ${{ secrets.USERNAME }}/${{ env.IMAGE_NAME }}:latest

       - name: Logout from Docker Registry
         if: always()
         run: docker logout